backbone:
  _target_: torch.hub.load
  repo_or_dir: dinov3
  # repo_or_dir: https://github.com/facebookresearch/dinov3
  model: dinov3_vits16plus
  source: local
  weights: weights/dinov3_vits16plus_pretrain_lvd1689m-4057cbaa.pth

# dino_head:
#   _target_: src.model.head.DINOHead
#   in_dim: 384
#   out_dim: 65536
#   use_bn: true
#   nlayers: 3
#   hidden_dim: 2048
#   bottleneck_dim: 256
#   mlp_bias: true

dino_head:
  _target_: src.model.head.DINOHead
  in_dim: 384
  out_dim: 4096
  # use_bn: true
  # nlayers: 3
  hidden_dim: 2048
  # bottleneck_dim: 256
  # mlp_bias: true

# ibot_head:
#   _target_: src.model.head.DINOHead
#   in_dim: 384
#   out_dim: 65536
#   use_bn: true
#   nlayers: 3
#   hidden_dim: 2048
#   bottleneck_dim: 256
#   mlp_bias: true

ibot_head:
  _target_: src.model.head.iBOTHead
  in_dim: 384
  out_dim: 1024
  # use_bn: true
  # nlayers: 3
  # hidden_dim: 384
  # bottleneck_dim: 256
  # mlp_bias: true

patch_size: 16

# 注意：模型配置中的图像尺寸由 data.image_size 控制
# 请修改 config/data/*.yaml 中的 image_size 参数